version: '3.7'

services:
  movie_service:
    build: ./movie_service
    image: movie_service:0.0.1
    container_name: movie_service
    #command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./movie_service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on: 
      - movie_db

  movie_db:
    image: postgres:12.1-alpine
    container_name: movie_db
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:  
      - POSTGRES_USER=movie_db_username
      - POSTGRES_PASSWORD=movie_db_password
      - POSTGRES_DB=movie_db_dev

  cast_service:
    build: 
      context: ./cast_service
      target: debug
    image: cast_service:0.0.1
    container_name: cast_service
    #command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast_service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
    depends_on: 
      - cast_db

  cast_db:
    image: postgres:12.1-alpine
    container_name: cast_db
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cast_db_username
      - POSTGRES_PASSWORD=cast_db_password
      - POSTGRES_DB=cast_db_dev

  user_service:
    build: 
      context: ./user_service
      target: debug
    image: user_service:0.0.1
    container_name: user_service
    #command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./user_service/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
    depends_on: 
      - user_db

  user_db:
    image: postgres:12.1-alpine
    container_name: user_db
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_db_username
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_DB=user_db_dev

  # nginx:
  #   image: nginx:1.19.2
  #   container_name: nginx
  #   ports:
  #       - 8080:8080
  #   volumes:
  #       - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #       - user_service
  #       - cast_service
  #       - movie_service
  #       - pgadmin

  nginx:
    build:
      context: ./angular-front
      target: run
    container_name: angular
    ports:
        - 8080:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        - user_service
        - cast_service
        - movie_service
        - pgadmin

  pgadmin:
    image: dpage/pgadmin4:4.25
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_DEFAULT_EMAIL: marciocadev@gmail.com
    ports:
      - 15432:80

volumes:
  postgres_data_movie:
  postgres_data_cast:
  postgres_data_user: