version: '3.7'

services:
  movie_service:
    build: ./movie_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie_service/:/app/
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URI=postgresql://postgres:admin2020@192.168.40.116:5432/movie_db
      - CAST_SERVICE_HOST_URL=http://192.168.40.116:8080/api/v1/casts/

  cast_service:
    build: ./cast_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast_service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://postgres:admin2020@192.168.40.116:5432/cast_db

  nginx:
    image: nginx:latest
    ports:
        - "8080:8080"
    volumes:
        - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - cast_service
        - movie_service
